export const Users = [
  {
    id: 1,
    profilePicture: "/person/1.jpg",
    username: "Emily Johnson",
  },
  {
    id: 2,
    profilePicture: "/person/2.jpg",
    username: "Daniel Miller",
  },
  {
    id: 3,
    profilePicture: "/person/3.jpg",
    username: "Olivia Green",
  },
  {
    id: 4,
    profilePicture: "/person/4.jpg",
    username: "Sophia Martinez",
  },
  {
    id: 5,
    profilePicture: "/person/5.jpg",
    username: "Liam Williams",
  },
  {
    id: 6,
    profilePicture: "/person/6.jpg",
    username: "Benjamin Thompson",
  },
  {
    id: 7,
    profilePicture: "/person/7.jpg",
    username: "Ava Robinson",
  },
  {
    id: 8,
    profilePicture: "/person/8.jpg",
    username: "William Davis",
  },
  {
    id: 9,
    profilePicture: "/person/9.jpg",
    username: "Mia Wilson",
  },
  {
    id: 10,
    profilePicture: "/person/10.jpg",
    username: "Emma Anderson",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Embrace kindness and positivity.",
    photo: "/post/1.jpg",
    date: "3 hours ago",
    userId: 5,
    like: 48,
    comment: 7,
  },
  {
    id: 2,
    photo: "/post/2.jpg",
    date: "6 hours ago",
    userId: 9,
    like: 13,
    comment: 4,
  },
  {
    id: 3,
    desc: "Cherish every moment you have.",
    photo: "/post/3.jpg",
    date: "1 day ago",
    userId: 4,
    like: 92,
    comment: 5,
  },
  {
    id: 4,
    photo: "/post/4.jpg",
    date: "2 days ago",
    userId: 8,
    like: 21,
    comment: 8,
  },
  {
    id: 5,
    photo: "/post/5.jpg",
    date: "3 days ago",
    userId: 1,
    like: 37,
    comment: 10,
  },
  {
    id: 6,
    photo: "/post/6.jpg",
    date: "4 days ago",
    userId: 7,
    like: 69,
    comment: 11,
  },
  {
    id: 7,
    desc: "Spread love and positivity everywhere.",
    photo: "/post/7.jpg",
    date: "1 week ago",
    userId: 10,
    like: 76,
    comment: 9,
  },
  {
    id: 8,
    photo: "/post/8.jpg",
    date: "2 weeks ago",
    userId: 3,
    like: 28,
    comment: 6,
  },
  {
    id: 9,
    desc: "Be yourself and inspire others.",
    photo: "/post/9.jpg",
    date: "3 weeks ago",
    userId: 6,
    like: 17,
    comment: 3,
  },
  {
    id: 10,
    photo: "/post/10.jpg",
    date: "1 month ago",
    userId: 2,
    like: 156,
    comment: 15,
  },
];
